<?php
return [
    'MERCHANT_ID' => env('MERCHANT_ID'),
    'MERCHANT_PASSWORD'=>env('MERCHANT_PASSWORD'),
    'PAYPAL_SANDBOX_API_USERNAME'=>env('PAYPAL_SANDBOX_API_USERNAME'),
    'PAYPAL_SANDBOX_API_PASSWORD'=>env('PAYPAL_SANDBOX_API_PASSWORD'),
    'PAYPAL_SANDBOX_API_SECRET'=>env('PAYPAL_SANDBOX_API_SECRET'),
    'PAYPAL_SANDBOX_API_CERTIFICATE'=>env('PAYPAL_SANDBOX_API_CERTIFICATE'),
    'MAIL_MAILER'=>env('MAIL_MAILER'),
    'MAIL_HOST'=>env('MAIL_HOST'),
    'MAIL_PORT'=>env('MAIL_PORT'),
    'MAIL_USERNAME'=>env('MAIL_USERNAME'),
    'MAIL_PASSWORD'=>env('MAIL_PASSWORD'),
    'MAIL_ENCRYPTION'=>env('MAIL_ENCRYPTION')
]
?>

